language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
sudo: false
script:
- sbt compile
- scripts/publishAndTag 'slamdata/sbt-slamdata'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+-.*$/"
env:
  global:
  - secure: QYLnqcmx9zna6dTcp9gaIKr+XzGaAbE8rBVEzkyRr6pFxRg4zADdLg+mxU03DszS0Sc5WnzrVzHlxEC3IH7EbjbCl3OyVFsfop+TVS0hz17EWHUdL5cvcgqPZRzT2N6bhcQ1KWEP188GPVBHayz11KNc/LCOS/YWJHYjzc6kRaNc7SRPY2pkF91zsy41eWwyuyj6hvMSm8H9nh2dBNIbzwUSg2FgzkvDsvQILwZC+9HWjMATyc5eh3BsdBGjVUqopiJkZLkrH/yf/VhNJSs0RkrgNFEUgY0QnI2ys3CpJ7zqTc7r/+z2H0PxTYX9G93+PbU23/erJbqdgwDH2RgBfqxrGRBrqIoGcUOc3TSf7qP0io0JM0nGw0F5SiB1sirPqYoXXAl/xLVtxVE018XgwpMrew6sFc2TQJfwOYRHJsYrmAzTGcgHScyLjqaQEZlJiP32rEPcaCQ3xiMNrYRrU1E0BXFEF3A4gyBx5oWNmBa02yv+N326DBv36K2pG8iAAZsNNBh6LG2tBhM82nWdmWlXq1/AXjowW15RenngOhexV90ETV2933iqM8DOWuenGbbYrD+SeZdLpur+kO9rSAuHczwVAtGO/qKIGCWOFP2kkhJgonZhm8J5IBpUvyKDnS4Hl18mQpOzqjoizF4NZgKziG1nUPCWpZ5EXUb/McQ=
deploy:
  provider: releases
  api_key:
    secure: MQnhpKqdfcnh4uEiHdcwb6+PDf5EP3jn2wQ1KZRgODLxn7hc2tNICG9kXHw3ehJ/5rY2E89tvc52FJTRjwD6jlWXtEs11cvOpF20cEE/8SMEk8bOp++0rSMLDu1XKOHpKU1dSzADJUs5SAtgc9/MfBx1rb5DCVKPXlRIaQ2N+OgmGyHxRQdeIhr0XU3qYNimBl7h1eFeYv1V46Tu8QuujDp2Y6qdVIqA0w10bwKLDTinuxlgyO9a2nxX161MhWuMCFgMTLTXgEWeY91UbnN49TjbNsQNiVFAru1k/vbrZQH7WXFWJ0tiaaKzaSJbt38FOxt8dXQ0sEv/l5hFW3/rDo+k/uoKk3v9Cn4AfHKzealje91eU1LoorP34QWNFOyevo8D56EPGJcQVRxrM1nujv0ZDldykS12u6wrb+iG40lh9FTKxVLTqzGIQh99tEPayG701MoHBdO2j2cHdPwc3dVHOH0u4YvcSjGZn22CbcGGH0HgI8t2R0okEW9ggkBjL/LQJqg0cUpllMKCjmk4VgxHITIKAUZVYCWyujfG6YRIlWM5YlacwUAzJQQ1qkh4xUD4RX8j4+Ad5IPlZ9Gz07kTuv4zqZVqORqr75CD83Fu07l886md0zs2C40MOT9+hV6dvNie/+pPNKSn5aYT8Z6NZZTZdkhpa1ypH4/0wt8=
  on:
    condition: ''
