language: scala
scala:
- 2.12.3
jdk:
- openjdk8
env:
- SBT="./sbt"
sudo: false
script:
- $SBT compile
- scripts/publishAndTag 'slamdata/sbt-slamdata'
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
